dist: xenial
language: csharp

before_install:
  - sudo chmod a+x ./scripts/install.sh
  - sudo chmod a+x ./scripts/build.sh
  - sudo chmod a+x ./scripts/deploy.sh
  - sudo apt-get update
  - sudo apt-get install -y unzip libgtk2.0-0 libsoup2.4-1 libarchive13 libgconf-2-4 p7zip-full gtk2.0 libnss3 tar zip gzip cpio

install:
  - ./scripts/install.sh

script:
  - ./scripts/build.sh

deploy:
  provider: script
  script: bash scripts/deploy.sh